### ISSUE TITLE
create a multi divice connection

### ISSUE THREAD

**Issue by LetsPoke** [knoffhoff/TheMillionaireGame#3]

**Comment by rz-p** [comment]
Local connection not possible within **AWS VPC/subnets** @LetsPoke 
Context: have exhausted every options in VPC and workspace settings. Ping and traceroute within the same subnet always RTO'd

Only possible to run the game with physical LAN devices only. Added documentation on [confluence page regarding local networking.](https://confluence.idealo.cloud/display/FP/Who+Wants+to+be+a+Millionaire#tab-Network+Settings)
